name: CI-CD

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AWS_REGION: us-east-1

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t tv-devops-app ./app

      - name: Tag Docker image
        run: docker tag tv-devops-app:latest ${{ secrets.ECR_URI }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_URI }}:latest

      - name: Install IaC dependencies
        working-directory: ./iac
        run: npm install

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli

      - name: Deploy infrastructure
        working-directory: ./iac
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_image_tag: latest
        run: |
          cdktf get
          cdktf deploy --auto-approve
